# Generated by Django 4.0.2 on 2022-02-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('source_ip', models.CharField(max_length=20)),
                ('destination_ip', models.CharField(max_length=20)),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('host', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('user_agent', models.CharField(max_length=100)),
                ('cookie', models.CharField(blank=True, max_length=500, null=True)),
                ('frame_size', models.IntegerField()),
                ('file_path', models.CharField(db_collation='utf8_general_ci', max_length=100)),
            ],
            options={
                'db_table': 'request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('source_ip', models.CharField(max_length=20)),
                ('destination_ip', models.CharField(max_length=20)),
                ('source_port', models.IntegerField()),
                ('destination_port', models.IntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('frame_size', models.IntegerField()),
                ('file_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'response',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whois',
            fields=[
                ('domain_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('registrant_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('registrar', models.CharField(blank=True, max_length=100, null=True)),
                ('registrar_phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'whois',
                'managed': False,
            },
        ),
    ]
