# Generated by Django 4.0.2 on 2022-02-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainManagement',
            fields=[
                ('domain_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('registrant_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('domain_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'domain_management',
                'managed': False,
            },
        ),
    ]
