# Generated by Django 3.2 on 2021-11-13 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=4)),
                ('cn', models.CharField(max_length=10)),
                ('cc', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ch', models.IntegerField()),
                ('ct', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.CharField(max_length=4)),
                ('sn', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=1)),
                ('majcla', models.CharField(max_length=10)),
                ('bir', models.DateField()),
                ('tel', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StudentHomework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('h2s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('h3s', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.student')),
            ],
        ),
    ]
