# Generated by Django 3.2 on 2021-11-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cc',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='ch',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='ct',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='bir',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='majcla',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='sn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='tel',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='h1s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='h2s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='studenthomework',
            name='h3s',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
