snifferRequest:
	gcc -o snifferRequest snifferRequest.c -lpcap

snifferRespnse:
 	gcc -o snifferRespnse snifferResponse.c -lpcap

handleRequest:
	gcc -o handleRequest handleRequest.c -lpcap -lmysqlclient

handleResponse:
	gcc -o handleResponse handleResponse.c -lpcap -lmysqlclient